- 👋 Holis, I’m @Uwawa19
- 👀 I’m interested in ver como me rompen el corazon  ...
- 🌱 I’m currently learning a desconfiar ...
- 💞️ I’m looking to collaborate on nada. ...
- 📫 How to reach me ni yo se...
- 😄 Pronouns: varios me han podado...
- ⚡ Fun fact: no merecia tratos, por q son del pasado y hay una explicacion...

<!---
Uwawa19/Uwawa19 is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
